version: '3'
services:
  database:
    container_name: database
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: core_users
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev
    ports:
      - "5433:5432"